### ISSUE TITLE
Can we have a release please?

### ISSUE THREAD

**Issue by JoeNyland** [bashaus/capistrano-autocomplete#4]
Hi there,

Thanks for writing this!

I hope you don't mind, but I submitted a PR over on the [Homebrew/homebrew-completions](https://github.com/Homebrew/homebrew-completions) repo to pull your script in to allow it to be easily installed using [Homebrew](https://github.com/Homebrew/brew).

Here's the PR: Homebrew/homebrew-completions#112.

As you can see, I've been asked to ask you if you would be willing to tag a release of your script before the PR will be merged. Would you be able to, please?

Cheers

**Comment by bashaus** [comment]
Solved (v1.0.0)

**Comment by JoeNyland** [comment]
@bashaus Thanks 👍
